version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${{ secrets.SUPABASE_URL}}
      - SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
    
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run build && npm start"
    restart: unless-stopped
