import { MigrationInterface, QueryRunner } from "typeorm";

export class PostsAutoGeneratedTable1753581415329
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TABLE posts (
          id SERIAL PRIMARY KEY,
          title VARCHAR(255) NOT NULL,
          description TEXT NOT NULL,
          content TEXT NOT NULL,
          subject VARCHAR(100),
          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
          updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
          user_id INTEGER NOT NULL
        )`);

    await queryRunner.query(`
        ALTER TABLE posts
        ADD CONSTRAINT fk_user
        FOREIGN KEY (user_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE
      `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE posts DROP CONSTRAINT fk_user`);
    await queryRunner.query(`DROP TABLE posts`);
  }
}
