import { MigrationInterface, QueryRunner } from "typeorm";

export class UsersAutoGeneratedTable1753575203651
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TYPE "public"."permission_type" AS ENUM ('0', '1')
      `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" SERIAL PRIMARY KEY,
        "username" varchar(50) NOT NULL,
        "password" varchar(100) NOT NULL,
        "email" varchar(100) NULL,
        "permission_type" "public"."permission_type" DEFAULT '0' NOT NULL
      ) `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "users"`);

    await queryRunner.query(`DROP TYPE "public"."permission_type"`);
  }
}
