import dotenv from "dotenv";
import { DataSource } from "typeorm";
import { UsersAutoGeneratedTable1753575203651 } from "../migrations/1753575203651-UsersAutoGeneratedTable";
import { PostsAutoGeneratedTable1753581415329 } from "../migrations/1753581415329-PostsAutoGeneratedTable";
import { Posts } from "../../entities/post.entity";
import { Users } from "../../entities/user.entity";


export const appDataSource = new DataSource({
  type: "postgres",
  url:  process.env.SUPABASE_URL,
  synchronize: false,
  ssl: true,
  logging: true,
  poolSize: 5,
  extra: {
    options: "-c timezone=UTC",
    ssl: {
      require: true,
      rejectUnauthorized: false,
    },
    connectionTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
  },
  entities : [ "dist/**/*.entity{.ts,.js}" ],
  migrations : [ "dist/lib/migrations/*{.ts,.js}" ]
});

appDataSource
  .initialize()
  .then(() => {
    console.log("Database with typeorm connected");
    return appDataSource.runMigrations();
  })
  .catch((err) => console.error(`Database with typeorm erro: ${err}`));
