import dotenv from "dotenv";
import { DataSource } from "typeorm";
import { Posts } from "@/entities/post.entity";
import { Users } from "@/entities/user.entity";
import { UsersAutoGeneratedTable1753575203651 } from "../migrations/1753575203651-UsersAutoGeneratedTable";
import { PostsAutoGeneratedTable1753581415329 } from "../migrations/1753581415329-PostsAutoGeneratedTable";


export const appDataSource = new DataSource({
  type: "postgres",
  url:  process.env.SUPABASE_URL,
  entities: [Users, Posts],
  synchronize: false,
  ssl: true,
  logging: true,
  poolSize: 5,
  extra: {
    options: "-c timezone=UTC",
    ssl: {
      rejectUnauthorized: false,
    },
    connectionTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
  },
  migrations: [
    UsersAutoGeneratedTable1753575203651,
    PostsAutoGeneratedTable1753581415329,
  ],
});

appDataSource
  .initialize()
  .then(() => {
    console.log("Database with typeorm connected");
    return appDataSource.runMigrations();
  })
  .catch((err) => console.error(`Database with typeorm erro: ${err}`));
