import dotenv from "dotenv";
import path from "path";
import { DataSource } from "typeorm";
import { Posts } from "@/entities/post.entity";
import { Users } from "@/entities/user.entity";
import { UsersAutoGeneratedTable1753575203651 } from "../migrations/1753575203651-UsersAutoGeneratedTable";
import { PostsAutoGeneratedTable1753581415329 } from "../migrations/1753581415329-PostsAutoGeneratedTable";

dotenv.config({
  path: path.resolve(__dirname, "..", ".env"),
});

export const appDataSource = new DataSource({
  type: "postgres",
  host: process.env.SUPABASE_URL,
  port: parseInt(process.env.DB_PORT || "6543"),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: "postgres",
  entities: [Users, Posts],
  synchronize: false,
  ssl: true,
  logging: true,
  poolSize: 5,
  extra: {
    options: "-c timezone=UTC",
    ssl: {
      require: true,
      rejectUnauthorized: false,
    },
  },
  migrations: [
    UsersAutoGeneratedTable1753575203651,
    PostsAutoGeneratedTable1753581415329,
  ],
});

appDataSource
  .initialize()
  .then(() => {
    console.log("Database with typeorm connected");
  })
  .catch((err) => console.error(`Database with typeorm erro: ${err}`));
